version: 1.0.0.{build}
os: Visual Studio 2015
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}-$(APPVEYOR_REPO_COMMIT)'
before_build:
- ps: nuget restore
build:
  project: Tabster.WinForms.sln
after_build:
- ps: >-
    .\nuget_pack.ps1
- ps: >-
    .\Deploy\archive.ps1
artifacts:
- path: '*.nupkg'
  name: nuget_package
- path: 'Tabster.WinForms.zip'
  name: archive
deploy:
  - provider: NuGet
    api_key:
      secure: QzhmxS67d/XC1o4iPuKUv4+m4DxLtf5xXivDgokPK3kkMRP586YrbNDWZIPF09+R
    skip_symbols: false
    artifact: nuget_package
    on:
      branch: master
  - provider: GitHub
    auth_token:
      secure: SD+1NPa8QJ8nAT9A4wsEog2pedpT8KaQebkDVB9mHbVze6nYABjcVzDa/5MXK0ZW
    artifact: archive
    draft: false
    on:
      branch: master
      appveyor_repo_tag: true