version: 1.0.0.{build}
os: Visual Studio 2015
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}-$(APPVEYOR_REPO_COMMIT)'
before_build:
- ps: nuget restore
build:
  project: Tabster.WinForms.sln
deploy:
  provider: NuGet
  api_key:
    secure: QzhmxS67d/XC1o4iPuKUv4+m4DxLtf5xXivDgokPK3kkMRP586YrbNDWZIPF09+R
  skip_symbols: false
  artifact: /.*\.nupkg/